### ISSUE TITLE
Add the skeleton script

### ISSUE THREAD

**Issue by tomschr** [EMaksy/reportdaily#2]
# Situation

We have no script ATM.

# Proposed Solution

Add a script `bin/reportdaily.py` with the following content:

**Subtasks**

* [x] A shebang line.
* [x] Import the `argparse` and `sys` module
* [x] A `parsecli(cliargs=None)` function:
   * [x] Create a argparser object.
   * [x] Add an epilog which should look similar to this: `Version <VERSION> written by <AUTHOR>`
   * [x] Return the parsed CLI arguments as argparser object.
* [x] A `main(cliargs=None)` function, calling the `parsecli()` function
* [x] A docstring for each function
* [x] A line `if __name__ == "__main__"` which distinguish between importing a script and running it

See my [example-cli-argparse.py gist](https://gist.github.com/tomschr/10837c2f7286b13d3ebc59e40d943188) for details.
