### ISSUE TITLE
Integrate bump2version

### ISSUE THREAD

**Issue by tomschr** [EMaksy/reportdaily#6]
# Situation

Currently, our version is integrated in the script. In most cases this is enough.

However, the current version is also needed in other places (documentation, READMEs, etc.). Keeping them in sync in all places when changing the version string is error-prone and cumbersome.

# Proposed Solution

Whenever you raise a version, the `bump2version` tool takes care of all the places where a version string is used.

**Subtasks**

* [x] create a config file `.bumpversion.cfg` in the repo's root directory
* [x] add entries for all files that contain a version string
* [ ] decide, if you want to add a commit and/or tag when you raise a version

# Further Information

https://github.com/c4urself/bump2version
