### ISSUE TITLE
Use the logging module

### ISSUE THREAD

**Issue by tomschr** [EMaksy/reportdaily#7]
# Situation

The script doesn't distinguish between user related messages and developer related messages. A normal `print()` is not enough.

# Proposed Solution

Use the [logging module](https://docs.python.org/3/library/logging.html#module-logging).

**Subtasks:**

* [x] Add a `-v` option to the argument parser.
 This option can be added multiple times to raise the logging level. The resulting argparser object needs to contain an integer between 0...4.
* [x] Map the verbosity level from `-v` to the logging level. 
  For example, if you omit the `-v` option, the verbosity level is zero (0). In that case, only errors and critical problems should be displayed (`logging.ERROR` and up).
* [x] Create a global logging object with `__name__`.
* [x] Use a dictionary to set the formatter, handler, and loggers. Pass this dictionary to [`logging.conf.dictConf`](https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig).
* [ ] Raise version.
