### ISSUE TITLE
Add a manpage

### ISSUE THREAD

**Issue by tomschr** [EMaksy/reportdaily#8]
# Situation

The script doesn't contain a manpage.

# Solution

I'd recommend to use [Sphinx](https://www.sphinx-doc.org). It's the most used doc format in the Python community.

All the documentation (including manpage) will end up in the `docs` directory.

**Subtasks**

* [x] Create the structure of the docs and Makefile with the script `sphinx-quickstart-3.?`, for example:

        $ sphinx-quickstart-3.? --no-batchfile --project reportdaily --author "Eugen Maksymenko" docs

* [x] Create a file `reportdaily.rst`; this is your file in RST format which contains your manpage.
* [x] Structure your manpage accordingly. Possible sections could be `NAME`, `SYNOPSIS`, `DESCRIPTION`, `EXAMPLES`, `FILES`, `BUGS`, `SEE ALSO`, `AUTHORS` etc.
* [x] Include `reportdaily.rst` into the main file `index.rst`.
* [x] Integrate the `docs` folder in `setup.cfg`. It needs to be included in the source distribution. Maybe adapt `MANIFEST.in` as well.
* [x] Integrate `docs/conf.py` into bump2version configuration.

# Additional information

* [Example manpage for pysemver tool](https://github.com/python-semver/python-semver/blob/master/docs/pysemver.rst)
